//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_1.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROYECTO_1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1100858_538957_900 {
            get {
                object obj = ResourceManager.GetObject("1100858_538957_900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1100858_538957_9001 {
            get {
                object obj = ResourceManager.GetObject("1100858_538957_9001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1100858_538957_9002 {
            get {
                object obj = ResourceManager.GetObject("1100858_538957_9002", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _942f45f677396f12605af464a9d79bab {
            get {
                object obj = ResourceManager.GetObject("942f45f677396f12605af464a9d79bab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _942f45f677396f12605af464a9d79bab1 {
            get {
                object obj = ResourceManager.GetObject("942f45f677396f12605af464a9d79bab1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _942f45f677396f12605af464a9d79bab2 {
            get {
                object obj = ResourceManager.GetObject("942f45f677396f12605af464a9d79bab2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af1b58420e07db682b001ed3b56d029c {
            get {
                object obj = ResourceManager.GetObject("af1b58420e07db682b001ed3b56d029c", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap af1b58420e07db682b001ed3b56d029c1 {
            get {
                object obj = ResourceManager.GetObject("af1b58420e07db682b001ed3b56d029c1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Alta_pasteleria_1024x576 {
            get {
                object obj = ResourceManager.GetObject("Alta-pasteleria-1024x576", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bakery_cakes_dessert_pastries_linear_pattern_doodle_vintage_food_icons_sweet_elements_background_for_menu_cafe_shop_flat_hand_drawn_vintage_set_free_vector {
            get {
                object obj = ResourceManager.GetObject("bakery-cakes-dessert-pastries-linear-pattern-doodle-vintage-food-icons-sweet-elem" +
                        "ents-background-for-menu-cafe-shop-flat-hand-drawn-vintage-set-free-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bakery_cakes_dessert_pastries_linear_pattern_doodle_vintage_food_icons_sweet_elements_background_for_menu_cafe_shop_flat_hand_drawn_vintage_set_free_vector1 {
            get {
                object obj = ResourceManager.GetObject("bakery-cakes-dessert-pastries-linear-pattern-doodle-vintage-food-icons-sweet-elem" +
                        "ents-background-for-menu-cafe-shop-flat-hand-drawn-vintage-set-free-vector1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap captura_de_pantalla_2022_03_10_a_las_91647_1024x761 {
            get {
                object obj = ResourceManager.GetObject("captura-de-pantalla-2022-03-10-a-las-91647-1024x761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dasd {
            get {
                object obj = ResourceManager.GetObject("dasd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap f8b81ad6df9121bacb0e41e2c4c15f09 {
            get {
                object obj = ResourceManager.GetObject("f8b81ad6df9121bacb0e41e2c4c15f09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FOTO_PORTADA_2 {
            get {
                object obj = ResourceManager.GetObject("FOTO-PORTADA-2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen1 {
            get {
                object obj = ResourceManager.GetObject("Imagen1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Imagen2___copia {
            get {
                object obj = ResourceManager.GetObject("Imagen2 - copia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_2075_5_112170 {
            get {
                object obj = ResourceManager.GetObject("img-2075_5_112170", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_2075_5_1121701 {
            get {
                object obj = ResourceManager.GetObject("img-2075_5_1121701", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1385051053_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1385051053-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1385051053_612x6121 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1385051053-612x6121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LOGO_CHEFSITO {
            get {
                object obj = ResourceManager.GetObject("LOGO CHEFSITO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pastel_tres_leches_de_chocolate {
            get {
                object obj = ResourceManager.GetObject("Pastel-tres-leches-de-chocolate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasteles_vectoriales_dibujados_a_mano_panaderia_postres_sin_costuras_patron_ilustracion_de_postre_de_panaderia_fondo_de_pasteleria_dulce_chocolate_y_cupcake_2d7n6je {
            get {
                object obj = ResourceManager.GetObject("pasteles-vectoriales-dibujados-a-mano-panaderia-postres-sin-costuras-patron-ilust" +
                        "racion-de-postre-de-panaderia-fondo-de-pasteleria-dulce-chocolate-y-cupcake-2d7n" +
                        "6je", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasteles_vectoriales_dibujados_a_mano_panaderia_postres_sin_costuras_patron_ilustracion_de_postre_de_panaderia_fondo_de_pasteleria_dulce_chocolate_y_cupcake_2d7n6je1 {
            get {
                object obj = ResourceManager.GetObject("pasteles-vectoriales-dibujados-a-mano-panaderia-postres-sin-costuras-patron-ilust" +
                        "racion-de-postre-de-panaderia-fondo-de-pasteleria-dulce-chocolate-y-cupcake-2d7n" +
                        "6je1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasteles_vectoriales_dibujados_a_mano_panaderia_postres_sin_costuras_patron_ilustracion_de_postre_de_panaderia_fondo_de_pasteleria_dulce_chocolate_y_cupcake_2d7n6je2 {
            get {
                object obj = ResourceManager.GetObject("pasteles-vectoriales-dibujados-a-mano-panaderia-postres-sin-costuras-patron-ilust" +
                        "racion-de-postre-de-panaderia-fondo-de-pasteleria-dulce-chocolate-y-cupcake-2d7n" +
                        "6je2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasteles_vectoriales_dibujados_a_mano_panaderia_postres_sin_costuras_patron_ilustracion_de_postre_de_panaderia_fondo_de_pasteleria_dulce_chocolate_y_cupcake_2d7n6je3 {
            get {
                object obj = ResourceManager.GetObject("pasteles-vectoriales-dibujados-a-mano-panaderia-postres-sin-costuras-patron-ilust" +
                        "racion-de-postre-de-panaderia-fondo-de-pasteleria-dulce-chocolate-y-cupcake-2d7n" +
                        "6je3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pasteles_vectoriales_dibujados_a_mano_panaderia_postres_sin_costuras_patron_ilustracion_de_postre_de_panaderia_fondo_de_pasteleria_dulce_chocolate_y_cupcake_2d7n6je4 {
            get {
                object obj = ResourceManager.GetObject("pasteles-vectoriales-dibujados-a-mano-panaderia-postres-sin-costuras-patron-ilust" +
                        "racion-de-postre-de-panaderia-fondo-de-pasteleria-dulce-chocolate-y-cupcake-2d7n" +
                        "6je4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_cafe_menu_dish_english_restaurant_menu_microphone_english_text {
            get {
                object obj = ResourceManager.GetObject("png-transparent-cafe-menu-dish-english-restaurant-menu-microphone-english-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TORTA_DE_CHOCOLATE {
            get {
                object obj = ResourceManager.GetObject("TORTA DE CHOCOLATE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhatsApp_Image_2023_10_23_at_22_18_28 {
            get {
                object obj = ResourceManager.GetObject("WhatsApp Image 2023-10-23 at 22.18.28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
